import type { NavItem, PageOption, ProductFlow } from "./types"

export const INITIAL_FLOWS: ProductFlow[] = [
  {
    id: "onboarding",
    title: "Onboarding — 學員綁定",
    description: "管理者新增學員後，學員透過 LINE OA 完成帳號綁定流程。",
    screens: [
      {
        id: "ob1",
        title: "新增學員",
        href: "/admin/students",
        type: "desktop",
        platform: "後台",
        role: "admin",
        purpose: "管理者建立學員資料，系統自動產生邀請碼並提供給學員。",
        states: ["default", "loading", "success"],
        x: 80,
        y: 140,
      },
      {
        id: "ob2",
        title: "加入 LINE OA",
        href: "/line",
        type: "mobile",
        platform: "LINE",
        role: "student",
        purpose: "學員加入 FitFlo 官方帳號，收到歡迎訊息與綁定連結。",
        states: ["default"],
        x: 420,
        y: 80,
      },
      {
        id: "ob3",
        title: "LIFF 綁定表單",
        href: "/liff/onboarding",
        type: "mobile",
        platform: "LIFF",
        role: "student",
        purpose: "學員填寫姓名、手機號碼與邀請碼完成帳號綁定。",
        states: ["default", "submitting", "error"],
        x: 680,
        y: 80,
      },
      {
        id: "ob4",
        title: "課表首頁",
        href: "/liff/schedule",
        type: "mobile",
        platform: "LIFF",
        role: "student",
        purpose: "綁定成功後進入學員主畫面，顯示課表與堂數。",
        states: ["default", "empty"],
        x: 940,
        y: 80,
      },
    ],
    edges: [
      { id: "e1", from: "ob1", to: "ob2", label: "邀請碼交接" },
      { id: "e2", from: "ob2", to: "ob3", label: "點擊綁定" },
      { id: "e3", from: "ob3", to: "ob4", label: "送出成功" },
    ],
  },
  {
    id: "booking",
    title: "排課 — 課程預約",
    description: "管理者建立課程後，學員透過 LINE 語意對話查詢並完成預約。",
    screens: [
      {
        id: "bk1",
        title: "課程管理",
        href: "/admin/courses",
        type: "desktop",
        platform: "後台",
        role: "admin",
        purpose: "管理者建立課程、設定時段、導師與名額上限。",
        states: ["default", "empty"],
        x: 80,
        y: 140,
      },
      {
        id: "bk2",
        title: "LINE 查詢課表",
        href: "/line",
        type: "mobile",
        platform: "LINE",
        role: "student",
        purpose: "學員輸入自然語言，AI 語意解析後顯示課程資訊。",
        states: ["default", "loading"],
        x: 420,
        y: 80,
      },
      {
        id: "bk3",
        title: "LIFF 課表",
        href: "/liff/schedule",
        type: "mobile",
        platform: "LIFF",
        role: "student",
        purpose: "學員瀏覽可預約課程，查看名額與教練資訊。",
        states: ["default", "empty", "loading"],
        x: 680,
        y: 80,
      },
      {
        id: "bk4",
        title: "導師查看名單",
        href: "/liff/coach",
        type: "mobile",
        platform: "LIFF",
        role: "coach",
        purpose: "導師查看本週課程與已報名學員名單，管理出席狀況。",
        states: ["default", "empty"],
        x: 940,
        y: 80,
      },
    ],
    edges: [
      { id: "e1", from: "bk1", to: "bk2", label: "課程上線" },
      { id: "e2", from: "bk2", to: "bk3", label: "開啟 LIFF" },
      { id: "e3", from: "bk3", to: "bk4", label: "預約完成" },
    ],
  },
  {
    id: "leave",
    title: "請假 — 申請與確認",
    description: "學員透過 AI 對話完成請假申請，導師直接在 LINE 確認回覆。",
    screens: [
      {
        id: "lv1",
        title: "LINE 請假對話",
        href: "/line",
        type: "mobile",
        platform: "LINE",
        role: "student",
        purpose: "學員說出請假意圖，AI 語意解析課程後引導確認。",
        states: ["intent", "selecting", "confirming"],
        x: 80,
        y: 80,
      },
      {
        id: "lv2",
        title: "LIFF 請假表單",
        href: "/liff/leave",
        type: "mobile",
        platform: "LIFF",
        role: "student",
        purpose: "學員選擇課程日期並填寫請假原因後送出申請。",
        states: ["default", "submitting", "success"],
        x: 340,
        y: 80,
      },
      {
        id: "lv3",
        title: "導師 LINE 確認",
        href: "/line",
        type: "mobile",
        platform: "LINE",
        role: "coach",
        purpose: "導師收到請假通知後，直接在 LINE 一鍵確認或拒絕。",
        states: ["default", "confirmed", "rejected"],
        x: 600,
        y: 80,
      },
      {
        id: "lv4",
        title: "請假紀錄",
        href: "/admin/leaves",
        type: "desktop",
        platform: "後台",
        role: "admin",
        purpose: "後台自動同步所有請假狀態，支援篩選與匯出報表。",
        states: ["default", "empty"],
        x: 850,
        y: 140,
      },
    ],
    edges: [
      { id: "e1", from: "lv1", to: "lv2", label: "開啟表單" },
      { id: "e2", from: "lv2", to: "lv3", label: "送出通知" },
      { id: "e3", from: "lv3", to: "lv4", label: "自動同步" },
    ],
  },
]

export const TREE: NavItem[] = [
  {
    id: "flows-root",
    label: "Flows",
    emoji: "⬡",
    type: "section",
    children: [
      {
        id: "role-student",
        label: "學員端",
        emoji: "👤",
        type: "role",
        children: [
          { id: "nav-onboarding", label: "Onboarding 綁定", type: "flow", flowId: "onboarding" },
          { id: "nav-booking", label: "課程預約", type: "flow", flowId: "booking" },
          { id: "nav-leave", label: "請假申請", type: "flow", flowId: "leave" },
        ],
      },
      {
        id: "role-coach",
        label: "教練端",
        emoji: "🏋️",
        type: "role",
        children: [
          { id: "nav-coach-today", label: "今日課表查詢", type: "flow", flowId: "booking" },
          { id: "nav-coach-leave", label: "請假確認", type: "flow", flowId: "leave" },
        ],
      },
      {
        id: "role-admin",
        label: "管理後台",
        emoji: "⚙️",
        type: "role",
        children: [
          { id: "nav-admin-students", label: "學員管理", type: "flow", flowId: "onboarding" },
        ],
      },
    ],
  },
  {
    id: "docs-root",
    label: "文件",
    emoji: "📄",
    type: "section",
    children: [
      { id: "doc-competitive", label: "競品分析", type: "doc", docId: "competitive" },
      { id: "doc-design", label: "設計規範", type: "doc", docId: "design" },
    ],
  },
]

export const PAGE_OPTIONS: PageOption[] = [
  { label: "LINE 對話", href: "/line", type: "mobile", platform: "LINE", role: "student" },
  { label: "LIFF 課表", href: "/liff/schedule", type: "mobile", platform: "LIFF", role: "student" },
  { label: "LIFF 請假表單", href: "/liff/leave", type: "mobile", platform: "LIFF", role: "student" },
  { label: "LIFF 綁定", href: "/liff/onboarding", type: "mobile", platform: "LIFF", role: "student" },
  { label: "LIFF 教練視圖", href: "/liff/coach", type: "mobile", platform: "LIFF", role: "coach" },
  { label: "後台 Dashboard", href: "/admin/dashboard", type: "desktop", platform: "後台", role: "admin" },
  { label: "後台 學員管理", href: "/admin/students", type: "desktop", platform: "後台", role: "admin" },
  { label: "後台 課程管理", href: "/admin/courses", type: "desktop", platform: "後台", role: "admin" },
  { label: "後台 請假紀錄", href: "/admin/leaves", type: "desktop", platform: "後台", role: "admin" },
  { label: "後台 設定", href: "/admin/settings", type: "desktop", platform: "後台", role: "admin" },
]
